/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coordinate = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Route = IDL.Record({
  'name' : IDL.Text,
  'waypoints' : IDL.Vec(Coordinate),
  'distance' : IDL.Float64,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'deleteRoute' : IDL.Func([IDL.Nat], [], []),
  'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
  'saveRoute' : IDL.Func([Route], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coordinate = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Route = IDL.Record({
    'name' : IDL.Text,
    'waypoints' : IDL.Vec(Coordinate),
    'distance' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'deleteRoute' : IDL.Func([IDL.Nat], [], []),
    'getRoutes' : IDL.Func([], [IDL.Vec(Route)], ['query']),
    'saveRoute' : IDL.Func([Route], [], []),
  });
};

export const init = ({ IDL }) => { return []; };